app/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView
from .signals import * #ensure that the signals are attatched via import
from django.contrib.auth import logout
from django.http import HttpResponseRedirect

urlpatterns = patterns('app.views',
    # Examples:
    url(r'^error/', 'error', name='error'),
    url(r'^404/', '_404', name='404'),
    url(r'^$', 'index', name='index'),
    url(r'^create_customer/', 'create_customer', name='create_customer'),
    url(r'^charge_customer/', 'charge_customer', name='charge_customer'),
    url(r'^$', TemplateView.as_view(template_name="index.html")),
    url(r'^survey', 'survey', name='survey'),
    url(r'^nutritionist/(?P<id>\d+)/$', 'nutritionist', name='nutritionist'),
    url(r'^recommended-nutritionists', 'recommended_nutritionists', name='recommended-nutritionists'),
    url(r'^schedule-consultation/(?P<id>\d+)/$', 'schedule_consultation', name='schedule-consultation'),
    url(r'^consultation/(?P<nutritionist_id>\d+)/(?P<consultation_id>\d+)/$', 'consultation', name='consultation'),
    url(r'^upcoming-consultations', 'upcoming_consultations', name='upcoming-consultations'),
    url(r'^my-nutritionists', 'my_nutritionists', name='my-nutritionists'),
    url(r'^about', 'about', name='about'),
    url(r'^terms', 'terms', name='terms'),
    url(r'^privacy', 'privacy', name='privacy'),
    url(r'^contact', 'contact', name='contact'),
)

def custom_logout(request):
    logout(request)
    return HttpResponseRedirect("/")


urlpatterns += patterns('app.views', (r'^logout/$', custom_logout))
urlpatterns += patterns('app.views', (r'', include('account.urls')))

app/models.py
from django.db import models
from django_extensions.db.models import AutoSlugField
from model_utils.models import TimeStampedModel
from django.forms import ModelForm, Textarea, TextInput, Select
from django.forms.extras.widgets import SelectDateWidget
from util.util import file_url


class Nutritionist(TimeStampedModel):

   NUTRITIONIST_TYPES = (
       ('dietician' , 'Registered Dietician'),
       ('certified_nutrition_specialist' , 'Certified nutrition specialist'),
       ('certified_clinical_nutritionist' , 'Certified clinical nutritionist'),
       ('diplomat' , 'Diplomat of the American Clinical Board of Nutrition'),
       ('holistic_nutritionist' , 'Holistic nutritionist'),
       ('certified_health_coach' , 'Certified health coach'),
       ('certified_nutritionist' , 'Certified nutritionist'),
       ('certified_nutrition_consultant' , 'Certified nutrition consultant'),
     )

   MEETING_TYPES = (
       ('in_person' , 'In Person'),
       ('phone_call' , 'Phone Call'),
       ('video_call' , 'Video Call'),
     )

   first_name = models.CharField(max_length=255)
   last_name = models.CharField(max_length=255)
   nutritionist_type = models.CharField(max_length=255, choices=NUTRITIONIST_TYPES)
   meeting_type = models.CharField(max_length=255, choices=MEETING_TYPES)
   tag_phrase = models.CharField(max_length=2048)
   address = models.CharField(max_length=255)
   city = models.CharField(max_length=255)
   state = models.CharField(max_length=255)
   zip = models.CharField(max_length=255)
   users = models.ManyToManyField('account.User', related_name='nutritionist_users', null=True, blank=True)
   consultation_description = models.CharField(max_length=4096)
   skype_name = models.CharField(max_length=255)
   headshot = models.ImageField(upload_to=file_url("/nutritionist_headshots"), default='/nutritionist_headshots/none.jpg')
   consultation_price = models.IntegerField()

   def first_last(self):
      return unicode(self.first_name) + " " + unicode(self.last_name)

   def get_full_name(self):
        return unicode(self.first_name) + " " + unicode(self.last_name) + "  " + unicode(self.city) + ", " + unicode(self.state)

   def __unicode__(self):
        return self.get_full_name()


class Consultation(TimeStampedModel):
   TIMES = (
        ('early', 'Early'),
        ('afternoon', 'Afternoon'),
        ('evening', 'Evening'),
   )

   user = models.ForeignKey('account.User', related_name='user_consultation', null=True, blank=True)
   nutritionist = models.ForeignKey('Nutritionist', related_name='nutritionist_consultation', null=True, blank=True)
   date = models.DateField()
   time = models.CharField(max_length=255, choices=TIMES)
   paid = models.BooleanField(default=False)

   def __unicode__(self):
        return unicode(self.user) + " and " + unicode(self.nutritionist) + " on " + unicode(self.date) + " in" + unicode(self.time)

class ConsultationForm(ModelForm):
   class Meta:
      from datetime import date
      current_year = date.today().year
      YEAR_CHOICES = [str(current_year), str(current_year + 1)]

      model = Consultation
      fields = ['date', 'time']
      widgets = {
          'date':SelectDateWidget(attrs={'class':'consultation-date'}, years=YEAR_CHOICES),
          'time':Select(attrs={'class':'consultation-time'}),
      }


class Credential(TimeStampedModel):
   CREDENTIAL_TYPE = (
      ('degree', 'Degree'),
      ('license', 'License'),
      ('course', 'Course'),
   )

   type = models.CharField(max_length=255, choices=CREDENTIAL_TYPE)
   description = models.CharField(max_length=1024)
   #nutritionist = models.ManyToManyField('Nutritionist', related_name='nutritionist_credential', null=True, blank=True)
   nutritionist = models.ForeignKey('Nutritionist', related_name='nutritionist_credential', null=True, blank=True)

   def __unicode__(self):
        #return self.nutritionist.get_full_name() + unicode(self.type) + " " + unicode(self.description)
        return unicode(self.type) + " " + unicode(self.description)

class Demographic(TimeStampedModel):
   DEMOGRAPHIC_TYPE = (
      ('adult', 'Adult'),
      ('senior', 'Senior'),
      ('christian', 'Christian'),
      ('muslim', 'Muslim'),
      ('jewish', 'Jewlish'),
      ('buddhists', 'Buddhists'),
      ('african_american', 'African American'),
      ('latino_american', 'Latino American'),
      ('asian_american', 'Asian American'),
   )

   type = models.CharField(max_length=255, choices=DEMOGRAPHIC_TYPE)
   nutritionist = models.ManyToManyField('Nutritionist', related_name='nutritionist_demographic', null=True, blank=True)

   def __unicode__(self):
        return unicode(self.type)


class Specialty(TimeStampedModel):
   SPECIALTY_TYPE = (
      ('anger_management', 'Anger Management'),
      ('aspergers', 'Asperger\'s'),
      ('divorce', 'Divorce'),
      ('domestic_violence', 'Domestic Violence'),
      ('relationships', 'Relationships'),
      ('spirituality', 'Spirituality'),
      ('stress', 'Stress'),
   )

   type = models.CharField(max_length=255, choices=SPECIALTY_TYPE)
   nutritionist = models.ManyToManyField('Nutritionist', related_name='nutritionist_specialty', null=True, blank=True)

   def __unicode__(self):
        return unicode(self.type)


class Availability(TimeStampedModel):
   monday_early = models.BooleanField(default=False)
   monday_afternoon = models.BooleanField(default=False)
   monday_evening = models.BooleanField(default=False)

   tuesday_early = models.BooleanField(default=False)
   tuesday_afternoon = models.BooleanField(default=False)
   tuesday_evening = models.BooleanField(default=False)

   wednesday_early = models.BooleanField(default=False)
   wednesday_afternoon = models.BooleanField(default=False)
   wednesday_evening = models.BooleanField(default=False)

   thursday_early = models.BooleanField(default=False)
   thursday_afternoon = models.BooleanField(default=False)
   thursday_evening = models.BooleanField(default=False)

   friday_early = models.BooleanField(default=False)
   friday_afternoon = models.BooleanField(default=False)
   friday_evening = models.BooleanField(default=False)

   saturday_early = models.BooleanField(default=False)
   saturday_afternoon = models.BooleanField(default=False)
   saturday_evening = models.BooleanField(default=False)

   sunday_early = models.BooleanField(default=False)
   sunday_afternoon = models.BooleanField(default=False)
   sunday_evening = models.BooleanField(default=False)

   nutritionist = models.ForeignKey('Nutritionist', related_name='nutritionist_availability', null=True, blank=True)

   def __unicode__(self):
        return ("  M " + unicode(self.monday_early) + " " + unicode(self.monday_afternoon) + " " + unicode(self.monday_evening) + " " + \
   "  T " + unicode(self.tuesday_early) + " " +  unicode(self.tuesday_afternoon) + " " + unicode(self.tuesday_evening) + " " + \
   "  W " + unicode(self.wednesday_early) + " " + unicode(self.wednesday_afternoon) + " " + unicode(self.wednesday_evening) + " " + \
   "  TR " + unicode(self.thursday_early) + " " + unicode(self.thursday_afternoon) + " " + unicode(self.thursday_evening) + " " + \
   "  F " + unicode(self.friday_early) + " " + unicode(self.friday_afternoon) + " " + unicode(self.friday_evening) + " " + \
   "  Sa " + unicode(self.saturday_early) + " " + unicode(self.saturday_afternoon) + " " + unicode(self.saturday_evening) + " " + \
   "  Su " + unicode(self.sunday_early) + " " + unicode(self.sunday_afternoon) + " " + unicode(self.sunday_evening))


class HealthSurvey(TimeStampedModel):
   GENDER = (('male', 'Male'), ('female', 'Female'))
   EXERCISE_FREQ = [(str(i),str(i)) for i in range(16)]
   HEALTH_GOALS = (('dummy','dummy'),('weight_management', 'Weight Management'), ('pregnancy', 'Pregnancy'), ('eating_disorder','Eating Disorder'),
    ('digestive_or_allergy_issue','Digestive or Allergy Issue'),('athletic_performance','Athletic Performance'),
     ('fatigue_or_stress_management','Fatigue or Stress Management'), ('just_being_more_healthy','Just Being More Healthy'))
   DIETARY_RESTRICTIONS = (('dummy','dummy'),('none','None'), ('gluten_free','Gluten Free'),('vegetarian','Vegetarian'),('vegan','Vergan'),
    ('dairy_free','Dairy Free'),('low_sodium','Low Sodium'),('kosher','Kosher'), ('halal','Halal'), ('organic','Organic'))

   gender = models.CharField(max_length=10, choices=GENDER, verbose_name='gender')
   dob = models.DateField(verbose_name='When is your date of birth?')
   weight = models.IntegerField(verbose_name='weight')
   height = models.CharField(max_length=10, verbose_name='height')
   exercise_freq = models.CharField(max_length=255, choices=EXERCISE_FREQ, verbose_name='how often do you exercise per week?')
   health_goals = models.CharField(max_length=255, choices=HEALTH_GOALS, verbose_name='what are your health goals?')
   dietary_restrictions = models.CharField(max_length=255, choices=DIETARY_RESTRICTIONS, verbose_name='do you have any dietary restrictions?')
   anything_else = models.CharField(max_length=4096, null=True, blank=True, verbose_name='anything else you would like us to know:')

   def __unicode__(self):
        return unicode(self.gender) + " " + unicode(self.dob)


class HealthSurveyForm(ModelForm):
   class Meta:
      BIRTH_YEAR_CHOICES = [str(i + 1915) for i in range(100)]
      model = HealthSurvey
      fields = ['gender', 'dob', 'weight', 'height', 'exercise_freq', 'health_goals', 'dietary_restrictions', 'anything_else']
      widgets = {
          'anything_else': Textarea(attrs={'cols':100, 'rows':10, 'class':'form-field'}),
          'weight': TextInput(attrs={'class':'form-field form-field-height-weight-size'}),
          'height': TextInput(attrs={'class':'form-field form-field-height-weight-size'}),
          'exercise_freq': Select(attrs={'class':'form-field form-field-dropdown-size'}),
          'health_goals': Select(attrs={'class':'form-field form-field-dropdown-size'}),

templates/about.html
{% extends "base.html" %}

{% block title %}
Nutrifeedback
{% endblock title %}

{% block content %}

<div class="container">

    <p class='section-title-static'> About </p>

    <p>Nutrifeedback connects people with health coaches and nutritionists anywhere, anytime. Our team is passionate about improving health. Nutrifeedback hope to help millions of people live healthier, happier lives. You deserve to feel better than ever. And with the right nutritional advice for you body, goals and lifestyle, we think you will.</p>
</div>

{% endblock content %}

templates/consultation.html
{% extends "base.html" %}

{% block title %}
Nutrifeedback
{% endblock title %}

{% block content %}
{% load static from staticfiles %}
<div class="outer-canvas">
  <div class="container">
  <div class="row line-no-pad">
    <div class="col-xs-2 no-pad"></div>
    <div class="col-xs-1 no-pad">
      <div class="top-spacer"><button class="back-button" onclick="history.back()">< BACK</button></div>
    </div>
  </div>
  <div class="inner-canvas">
    <div class="row line-no-pad">
      {% include 'snippets/candy_line.html' %}
    </div>
    <div class="inner-margin">
      <div class="row line-no-pad">
        <div class="left-section-title">Consultation with {{ nutritionist.first_name }} {{ nutritionist.last_name }}</div>
        <div class="row line-no-pad">
          <div class="section-title-detail">
            <p></p>
          </div>
        </div>
      </div>
      <div class="profile-divider-line"></div>
      <div id="nutritionist-block-margin">
        <div class="row">
          <div class="col-xs-2">
            <img class="circular-headshot" id="recommended-headshot" src="{{ nutritionist.headshot.url }}">
          </div>
          <div class="col-xs-10 no-pad">
            <div class="row">
              <div id="recommended-name">
                {{ nutritionist.first_name }} {{ nutritionist.last_name }},&nbsp
              </div>
              <div id="recommended-type">
                {{ nutritionist.get_nutritionist_type_display }}
              </div>
              <div id="meeting-type">
                ({{ nutritionist.get_meeting_type_display }})
              </div>
            </div>
            <div class="row">
              <div class="consultation-subheading">
                My Consultation Appointment:
              </div>
            </div>
            <div class="row">
              <div id="nutritionist-will-confirm">
                ({{ nutritionist.first_name }} will get back to you to confirm this consultation within 24 hours)
              </div>
            </div>
            <div class="row">
            </div>
            <div class="consultation-details-block">
            <div class="row consultation-details-spacer" id="">
              <div class="col-xs-1 no-pad">
                <img src='{% static 'img/date.png' %}'/>
              </div>
              <div class="col-xs-6 no-pad">
                <div class="consultation-details">{{ consultation.date }}</div>
              </div>
            </div>
            <div class="row consultation-details-spacer" id="">
              <div class="col-xs-1 no-pad">
                <img src='{% static 'img/time.png' %}'/>
              </div>
              <div class="col-xs-11 no-pad">
                <div class="consultation-details">{{ consultation.get_time_display }}</div>
              </div>
            </div>
            <div class="row consultation-details-spacer" id="">
              <div class="col-xs-1 no-pad">
                <img src='{% static 'img/pin.png' %}'/>
              </div>
              <div class="col-xs-11 no-pad">
               <div class="consultation-details">{{ nutritionist.address }}. {{ nutritionist.city }}, {{ nutritionist.state }} {{ nutritionist.zip }}</div>
              </div>
            </div>
            <div class="row consultation-details-spacer" id="">
              <div class="col-xs-1 no-pad">
                <img src='{% static 'img/skype.png' %}'/>
              </div>
              <div class="col-xs-11 no-pad">
                <div class="consultation-details">{{ nutritionist.skype_name }}</div>
              </div>
            </div>
            </div>

            <div class="row">

<!--              <div class="col-xs-4 no-pad">
              <a class="btn btn-primary no-pad" id="message-reschedule" href="{% url 'nutritionist' 1 %}">Message to Reschedule</a>
            </div>
 -->
             <div class="col-xs-4 no-pad">
               <a class="btn btn-primary" id="pay-button" href="#">Pay</a>
            </div>
            <div class="row">
              <div class="col-xs-12 no-pad">
                </br>AVAILABLE</br>
                {% include 'snippets/availability-table.html' %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="bottom-spacer"></div>
</div>
<div class="recommended-bottom-spacer"></div>
</div>
</div>

<script src="https://checkout.stripe.com/v2/checkout.js"></script>

<script>
 chargeCustomer = function(amount, nutritionist, consultation){
   $("<form method='post' action='{% url "charge_customer" %}'>{% csrf_token %}<input name='amount' value=" + amount +"><input name='nutritionist' value=" + nutritionist +"><input name='consultation' value=" + consultation +"></form>").appendTo("body").submit();
 }
</script>

<script>
{% if user_has_stripe_account == True %}
   document.getElementById('pay-button').addEventListener('click', function(e) {
      console.log("clicked on pay with stripe account");
      var amount = {{ nutritionist.consultation_price }};
      var nutritionist = {{ nutritionist.id }};
      var consultation = {{consultation.id }};
      chargeCustomer(amount, nutritionist, consultation);
   });
{% else %}
   var handler = StripeCheckout.configure({
      key: "{{SETTINGS.STRIPE_PUBLIC_KEY}}",
      image: "{% static 'img/home_logo.png' %}",
      token: function(token, args) {
         $.post("{% url 'create_customer' %}", token).then(function(){
            var amount = {{ nutritionist.consultation_price }};
            var nutritionist = {{ nutritionist.id }};
            var consultation = {{consultation.id }};
            response = chargeCustomer(amount, nutritionist, consultation);
         })
      }
   });
   document.getElementById('pay-button').addEventListener('click', function(e) {
    // Open Checkout with further options
      handler.open({
         name: 'Nutrifeedback',
         description: 'Consultation with {{ nutritionist.first_name }} {{ nutritionist.last_name }}',
         amount: {{ stripe_price }},
         email: '{{ user.email }}',
         allowRememberMe: false,
       });
    e.preventDefault();
   });
{% endif %}
</script>
{% endblock content %}

templates/contact.html
{% extends "base.html" %}

{% block title %}
Nutrifeedback
{% endblock title %}

{% block content %}

<div class="container">

    <p class='section-title-static'>Contact us</p>

    <p>Feel free to contact us at hello@nutrifeedback if you have any questions or suggestions to us at Nutrifeedback. </p>
</div>
{% endblock content %}

templates/footer.html
{% load static from staticfiles %}
  {% block footer %}
      <div class="container">
      <div class="footer-padding">
        <div class="row">
          <div class="col-xs-9">
            <div class="col-xs-2"><a class="footer-link" href="{% url 'about' %}">About</a></div>
            <div class="col-xs-2"><a class="footer-link" href="{% url 'terms' %}">Terms</a></div>
            <div class="col-xs-2"><a class="footer-link" href="{% url 'privacy' %}">Privacy</a></div>
            <div class="col-xs-3"><a class="footer-link" href="{% url 'contact' %}">Contact Us</a></div>
          </div>
          <div class="col-xs-3">
            <div id="icon-block">
              <div class="row">
                <a href="#"><img src='{% static 'img/twitter_icon.png' %}'/><a>
                <a href="#"><img src='{% static 'img/facebook_icon.png' %}'/><a>
                <a href="#"><img src='{% static 'img/pinterest_icon.png' %}'/><a>
               <a href="#"><img src='{% static 'img/instagram_icon.png' %}'/><a>
                <div class="clear"></div>
              </div>
            </div>
         </div>
      </div>
        <div class="row">
          <div class="col-xs-10">
            <p class="footer-copyright">Copyright &copy; 2014 Nutrifeedback. All Rights Reserved</p>
          </div>
        </div>
     </div>
  </div>
  {% endblock %}
</div>

templates/my-nutritionists.html
{% extends "base.html" %}

{% block title %}
Nutrifeedback
{% endblock title %}

{% block content %}
{% load static from staticfiles %}
  <div class="outer-canvas">
  <div class="container">
      <div class="row line-no-pad">
        <div class="col-xs-2 no-pad"></div>
        <div class="col-xs-1 no-pad">
          <div class="top-spacer"><button class="back-button" onclick="history.back()">< BACK</button></div>
        </div>
      </div>
    <div class="inner-canvas">

      <div class="row line-no-pad">
      {% include 'snippets/candy_line.html' %}
      </div>

      <div class="inner-margin">
      <div class="row line-no-pad">
        <div class="left-section-title">My Nutritionists</div>
        <div class="row line-no-pad">
          <div class="section-title-detail">
            <p>Here are the nutritionists you’ve connected with so far. Each time you schedule a consultation with a nutritionist, we’ll add them to your list.</p>
          </div>
        </div>
      </div>

      {% if consultations|length != 0 %}
        {% for consultation in consultations %}
          <div class="divider-line"></div>
          <div id="nutritionist-block-margin">
          <div class="row">
            <div class="col-xs-2">
              <img class="circular-headshot" id="recommended-headshot" src="{{ consultation.nutritionist.headshot.url }}">
            </div>
            <div class="col-xs-10 no-pad">
              <div class="row">
                <div id="recommended-name">
                  {{ consultation.nutritionist.first_name }} {{ consultation.nutritionist.last_name }},&nbsp
                </div>
                <div id="recommended-type">
                  {{ consultation.nutritionist.get_nutritionist_type_display }}
                </div>
              </div>
              <div class="row" id="recommended-city">
                <img id="pin" src='{% static 'img/pin.png' %}'/>
                {{ consultation.nutritionist.city }}
              </div>
              <div class="row" id="recommended-consultation">
                {{ consultation.nutritionist.consultation_description }}
              </div>
              <div>
                <div class="row">
                  <a class="btn btn-primary no-pad" id="view-profile" href="{% url 'consultation' consultation.nutritionist.id consultation.id%}">View My Consultation</a>
                </div>
              </div>
            </div>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <div class="divider-line"></div>
        <center>
          <div id="no-nutritionists">You don't have any nutritionists</div>
          <a class="btn btn-primary no-pad" id="add-nutritionists" href="{% url 'recommended-nutritionists' %}">Add Nutritionists</a>
        </center>
        <div id="no-nutritionist-padding"></div>
      {% endif %}
      </div>
      <div class="last-button-spacer"></div>
    </div>
    <div class="recommended-bottom-spacer"></div>
  </div>
</div>
{% endblock content %}

templates/nutritionist-email.html
nutritionist email html {{ domain }}

templates/recommended-nutritionists.html
{% extends "base.html" %}

{% block title %}
Nutrifeedback
{% endblock title %}

{% block content %}
{% load static from staticfiles %}
  <div class="outer-canvas">
  <div class="container">
      <div class="row line-no-pad">
        <div class="col-xs-2 no-pad"></div>
        <div class="col-xs-1 no-pad">
          <div class="top-spacer"><button class="back-button" onclick="history.back()">< BACK</button></div>
        </div>
      </div>
    <div class="inner-canvas">

      <div class="row line-no-pad">
      {% include 'snippets/candy_line.html' %}
      </div>

      <div class="inner-margin">
      <div class="row line-no-pad">
        <div class="left-section-title">We Recommend These Nutritionists For You</div>
        <div class="row line-no-pad">
          <div class="section-title-detail">
            <p>Here are your top nutritionist matches based on their specialty and location.</p>
          </div>
        </div>
      </div>

      {% for nutritionist in nutritionists %}
        <div class="divider-line"></div>
        <div id="nutritionist-block-margin">
        <div class="row">
          <div class="col-xs-2">
            <img class="circular-headshot" id="recommended-headshot" src="{{ nutritionist.headshot.url }}">
          </div>
          <div class="col-xs-10 no-pad">
            <div class="row">
              <div id="recommended-name">
                {{ nutritionist.first_name }} {{ nutritionist.last_name }},&nbsp
              </div>
              <div id="recommended-type">
                {{ nutritionist.get_nutritionist_type_display }}
              </div>
            </div>
            <div class="row" id="recommended-city">
              <img id="pin" src='{% static 'img/pin.png' %}'/>
              {{ nutritionist.city }}
            </div>
            <div class="row" id="recommended-consultation">
              {{ nutritionist.consultation_description }}
            </div>
            <div>
              <div class="row">
                <a class="btn btn-primary no-pad view-profile-button" href="{% url 'nutritionist' nutritionist.id %}">View Profile</a>
              </div>
            </div>
          </div>
          </div>
        </div>
      {% endfor %}


    </div>
<div class="last-button-spacer"></div>
    </div>
  <div class="recommended-bottom-spacer"></div>
  </div>
</div>
{% endblock content %}

templates/upcoming-consultations.html
{% extends "base.html" %}

{% block title %}
Nutrifeedback
{% endblock title %}

{% block content %}
{% load static from staticfiles %}
  <div class="outer-canvas">
  <div class="container">
      <div class="row line-no-pad">
        <div class="col-xs-2 no-pad"></div>
        <div class="col-xs-1 no-pad">
          <div class="top-spacer"><button class="back-button" onclick="history.back()">< BACK</button></div>
        </div>
      </div>
    <div class="inner-canvas">

      <div class="row line-no-pad">
      {% include 'snippets/candy_line.html' %}
      </div>

      <div class="inner-margin">
      <div class="row line-no-pad">
        <div class="left-section-title">Upcoming Consultations</div>
        <div class="row line-no-pad">
          <div class="section-title-detail">
            <p>Here are your upcoming nutritionist visits. </p>
          </div>
        </div>
      </div>

      {% for consultation in consultations %}
        <div class="divider-line"></div>
        <div id="nutritionist-block-margin">
        <div class="row">
          <div class="col-xs-2">
            <img class="circular-headshot" id="recommended-headshot" src="{{ consultation.nutritionist.headshot.url }}">
          </div>
          <div class="col-xs-10 no-pad">
            <div class="row">
              <div id="recommended-name">
                {{ consultation.nutritionist.first_name }} {{ consultation.nutritionist.last_name }},&nbsp
              </div>
              <div id="recommended-type">
                {{ consultation.nutritionist.get_nutritionist_type_display }}
              </div>
            </div>
            <div class="row" id="recommended-city">
              <img id="pin" src='{% static 'img/pin.png' %}'/>
              {{ consultation.nutritionist.city }}
            </div>
            <div class="row" id="recommended-consultation">
              {{ consultation.nutritionist.consultation_description }}
            </div>
            <div>
              <div class="row">
                <a class="btn btn-primary no-pad view-profile-button" href="{% url 'nutritionist' consultation.nutritionist.id %}">View Profile</a>
              </div>
            </div>
          </div>
          </div>
        </div>
      {% endfor %}


    </div>
<div class="last-button-spacer"></div>
    </div>
  <div class="recommended-bottom-spacer"></div>
  </div>
</div>
{% endblock content %}

templates/user-email.html
user email html
{{ domain }}
{{ consultation.user.get_full_name }}
{{ consultation.user.email }}
{{ consultation.date }}
{{ consultation.time }}
{{ user.first_name }}